import { useRouter } from 'next/router';
import styles from '../styles/Nav.module.css';
import Head from 'next/head'

export const Nav = ( props ) => {
    const router = useRouter();

    return (
        <div className={styles.navContainer}>
            <Head>
                { props.title ? <title>NJ Shore Art | {props.title} </title>: <title>NJ Shore Art</title> }
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div onClick={(() => router.push('/'))}>Home</div>
            <a target="_blank" href="https://instagram.com/njshoreart" rel="noopener noreferrer">Instagram</a>
            <a target="_blank" href="https://instagram.com/njshoreart" rel="noopener noreferrer">Venmo</a>
        </div>
    )
}