import Link from 'next/link'
import styles from '../styles/Nav.module.css';
import Head from 'next/head'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHouseChimney } from '@fortawesome/free-solid-svg-icons'
import { faInstagram, faVenmo } from '@fortawesome/free-brands-svg-icons'

export const Nav = (props) => {

   return (
      <div className={styles.navContainer}>
         <Head>
            {props.title ? <title>NJ Shore Art | {props.title} </title> : <title>NJ Shore Art</title>}
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className={styles.shoreIcon}>
            <Link href='/'>
               <a>
                  NJ Shore Art
                  {/* <FontAwesomeIcon icon={faHouseChimney} /> */}
               </a>
            </Link>
         </div>
         <div className={styles.navIcons}>
            <Link href='/'>
               <a>
                  Home
                  {/* <FontAwesomeIcon icon={faHouseChimney} /> */}
               </a>
            </Link>
            |
            <Link href="https://instagram.com/njshoreart">
               <a target="_blank" rel="noopener noreferrer">
                  Instagram
                  {/* <FontAwesomeIcon icon={faInstagram} /> */}
               </a>
            </Link>
            |
            <Link href="https://instagram.com/njshoreart">
               <a target="_blank" rel="noopener noreferrer">
                  Venmo
                  {/* <FontAwesomeIcon icon={faVenmo} /> */}
               </a>
            </Link>
         </div>
      </div>
   )
}