import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Nav.module.css';
import Head from 'next/head'
import logo from '../public/images/njshorelogo.png'

export const Nav = (props) => {

   return (
      <div className={styles.navContainer}>
         <Head>
            {props.title ? <title>NJ Shore Art | {props.title} </title> : <title>NJ Shore Art</title>}
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className={styles.shoreIcon}>
            <Link href='/'>
               <a>
                  NJ Shore Art
               </a>
            </Link>
         </div>
         <div className={styles.shoreLogo}>
            <Link href='/'>
               <a>
                  <Image
                     src={logo}
                  />
               </a>
            </Link>
         </div>
         <div className={styles.navIcons}>
            <Link href='/'>
               <a>
                  Home
               </a>
            </Link>
            |
            <Link href="https://instagram.com/njshoreart">
               <a target="_blank" rel="noopener noreferrer">
                  Instagram
               </a>
            </Link>
            |
            <Link href="https://instagram.com/njshoreart">
               <a target="_blank" rel="noopener noreferrer">
                  Venmo
               </a>
            </Link>
         </div>
      </div>
   )
}